from typing import List, NamedTuple


class Symbol(NamedTuple):
    name: str
    symbol_marketstack: str
    symbol_tradingview: str


SYMBOLS: List[Symbol] = [
    Symbol("ABB Ltd", "ABB.XSTO", "OMXSTO:ABB"),
    Symbol("Adidas AG", "ADS.XETRA", "XETR:ADS"),
    Symbol("Advanced Micro Devices, Inc.", "AMD", "NASDAQ:AMD"),
    Symbol("Airbus Group SE", "AIR.XETRA", "XETR:AIR"),
    Symbol("Alfa Laval AB", "ALFA.XSTO", "OMXSTO:ALFA"),
    Symbol("Alphabet Inc. - Class C Capital Stock", "GOOG", "NASDAQ:GOOG"),
    Symbol("Amazon.com, Inc.", "AMZN", "NASDAQ:AMZN"),
    Symbol("Apple Inc.", "AAPL", "NASDAQ:AAPL"),
    Symbol("ASSA ABLOY AB ser. B", "ASSA_B.XSTO", "OMXSTO:ASSA_B"),
    Symbol("AstraZeneca PLC", "AZN.XSTO", "OMXSTO:AZN"),
    Symbol("Atlas Copco AB ser. A", "ATCO_A.XSTO", "OMXSTO:ATCO_A"),
    Symbol("Atrium Ljungberg AB ser. B", "ATRLJ_B.XSTO", "OMXSTO:ATRLJ_B"),
    Symbol("Autoliv Inc. SDB", "ALIV_SDB.XSTO", "OMXSTO:ALIV_SDB"),
    Symbol("Avanza Bank Holding AB", "AZA.XSTO", "OMXSTO:AZA"),
    Symbol("Axfood AB", "AXFO.XSTO", "OMXSTO:AXFO"),
    Symbol("Bavarian Nordic A/S", "BAVA.XCSE", "OMXCOP:BAVA"),
    Symbol("Bayerische Motoren Werke AG", "BMW.XETRA", "XETR:BMW"),
    Symbol("Betsson AB ser. B", "BETS_B.XSTO", "OMXSTO:BETS_B"),
    Symbol("BillerudKorsnäs AB", "BILL.XSTO", "OMXSTO:BILL"),
    Symbol("Boliden AB", "BOL.XSTO", "OMXSTO:BOL"),
    Symbol("Bonava AB ser. B", "BONAV_A.XSTO", "OMXSTO:BONAV_A"),
    Symbol("Boozt AB", "BOOZT.XSTO", "OMXSTO:BOOZT"),
    Symbol("Boule Diagnostics AB", "BOUL.XSTO", "OMXSTO:BOUL"),
    Symbol("Bure Equity AB", "BURE.XSTO", "OMXSTO:BURE"),
    Symbol("Cargotec Oyj", "CGCBV.XHEL", "OMXHEX:CGCBV"),
    Symbol("Carlsberg B A/S", "CARL_A.XCSE", "OMXCOP:CARL_A"),
    Symbol("Catena Media P.L.C", "CTM.XSTO", "OMXSTO:CTM"),
    Symbol("CELLINK AB ser. B", "CLNK_B.XSTO", "OMXSTO:CLNK_B"),
    Symbol("Collector AB", "COLL.XSTO", "OMXSTO:COLL"),
    Symbol("Coloplast B A/S", "COLO_B.XCSE", "OMXCOP:COLO_B"),
    Symbol("D/S Norden", "DNORD.XCSE", "OMXCOP:DNORD"),
    Symbol("Daimler AG", "DAI.XETRA", "XETR:DAI"),
    Symbol("Danske Bank A/S", "DANSKE.XCSE", "OMXCOP:DANSKE"),
    Symbol("Deutsche Bank AG", "DBK.XETRA", "XETR:DBK"),
    Symbol("Diös Fastigheter AB", "DIOS.XSTO", "OMXSTO:DIOS"),
    Symbol("DNB", "DNB.XOSL", "OSL:DNB"),
    Symbol("DNO", "DNO.XOSL", "OSL:DNO"),
    Symbol("DSV Panalpina A/S", "DSV.XCSE", "OMXCOP:DSV"),
    Symbol("Electrolux, AB ser. B", "ELUX_B.XSTO", "OMXSTO:ELUX_B"),
    Symbol("Elekta AB ser. B", "EKTA_B.XSTO", "OMXSTO:EKTA_B"),
    Symbol("Elisa Corporation", "ELISA.XHEL", "OMXHEX:ELISA"),
    Symbol("Embracer Group AB ser. B", "EMBRAC_B.XSTO", "OMXSTO:EMBRAC_B"),
    Symbol("EQT AB", "EQT.XSTO", "OMXSTO:EQT"),
    Symbol("Ericsson, Telefonab. L M ser. B", "ERIC_B.XSTO", "OMXSTO:ERIC_B"),
    Symbol("Essity AB ser. B", "ESSITY_A.XSTO", "OMXSTO:ESSITY_A"),
    Symbol("Evolution Gaming Group AB", "EVO.XSTO", "OMXSTO:EVO"),
    Symbol("Fabege AB", "FABG.XSTO", "OMXSTO:FABG"),
    Symbol("Facebook A", "FB", "NASDAQ:FB"),
    Symbol("Fastighets AB Balder ser. B", "BALD_B.XSTO", "OMXSTO:BALD_B"),
    Symbol("Fingerprint Cards AB ser. B", "FING_B.XSTO", "OMXSTO:FING_B"),
    Symbol("Finnair Oyj", "FIA1S.XHEL", "OMXHEX:FIA1S"),
    Symbol("Fortum Corporation", "FORTUM.XHEL", "OMXHEX:FORTUM"),
    Symbol("Genmab A/S", "GMAB.XCSE", "OMXCOP:GMAB"),
    Symbol("Getinge AB ser. B", "GETI_B.XSTO", "OMXSTO:GETI_B"),
    Symbol("GN Store Nord A/S", "GN.XCSE", "OMXCOP:GN"),
    Symbol("Gold", "IAU", "IAU"),
    Symbol("Hansa Biopharma AB", "HNSA.XSTO", "OMXSTO:HNSA"),
    Symbol("Hennes & Mauritz AB, H & M ser. B", "HM_B.XSTO", "OMXSTO:HM_B"),
    Symbol("Hexagon AB ser. B", "HEXA_B.XSTO", "OMXSTO:HEXA_B"),
    Symbol("HEXPOL AB ser. B", "HPOL_B.XSTO", "OMXSTO:HPOL_B"),
    Symbol("Hoist Finance AB", "HOFI.XSTO", "OMXSTO:HOFI"),
    Symbol("Holmen AB ser. B", "HOLM_A.XSTO", "OMXSTO:HOLM_A"),
    Symbol("Hufvudstaden AB ser. A", "HUFV_A.XSTO", "OMXSTO:HUFV_A"),
    Symbol("Husqvarna AB ser. B", "HUSQ_A.XSTO", "OMXSTO:HUSQ_A"),
    Symbol("ICA Gruppen AB", "ICA.XSTO", "OMXSTO:ICA"),
    Symbol("Industrivärden, AB ser. C", "INDU_C.XSTO", "OMXSTO:INDU_C"),
    Symbol("Intel Corporation", "INTC", "NASDAQ:INTC"),
    Symbol("Intrum AB", "INTRUM.XSTO", "OMXSTO:INTRUM"),
    Symbol("Investor AB ser. B", "INVE_B.XSTO", "OMXSTO:INVE_B"),
    Symbol("JM AB", "JM.XSTO", "OMXSTO:JM"),
    Symbol("KAHOOT", "KAHOOT_ME.XOSL", "OSL:KAHOOT_ME"),
    Symbol("Kindred Group plc", "KIND_SDB.XSTO", "OMXSTO:KIND_SDB"),
    Symbol("Kinnevik AB ser. B", "KINV_B.XSTO", "OMXSTO:KINV_B"),
    Symbol("KONE Corporation", "KNEBV.XHEL", "OMXHEX:KNEBV"),
    Symbol("LeoVegas AB", "LEO.XSTO", "OMXSTO:LEO"),
    Symbol("Lundin Mining Corporation", "LUMI.XSTO", "OMXSTO:LUMI"),
    Symbol("Mastercard Incorporated", "MA", "NASDAQ:MA"),
    Symbol("Micron Technology, Inc.", "MU", "NASDAQ:MU"),
    Symbol("Microsoft Corporation", "MSFT", "NASDAQ:MSFT"),
    Symbol(
        "Millicom International Cellular S.A. SDB", "TIGO_SDB.XSTO", "OMXSTO:TIGO_SDB"
    ),
    Symbol("Modern Times Group MTG AB ser. B", "MTG_B.XSTO", "OMXSTO:MTG_B"),
    Symbol("NCC AB ser. B", "NCC_B.XSTO", "OMXSTO:NCC_B"),
    Symbol("NEL", "NELO.XSTO", "OMXSTO:NELO"),
    Symbol("Neste Corporation", "NESTE.XHEL", "OMXHEX:NESTE"),
    Symbol("Netflix, Inc.", "NFLX", "NASDAQ:NFLX"),
    Symbol("NIBE Industrier AB ser. B", "NIBE_B.XSTO", "OMXSTO:NIBE_B"),
    Symbol("NKT A/S", "NKT.XCSE", "OMXCOP:NKT"),
    Symbol("Nokia Corporation", "NOKIA.XHEL", "OMXHEX:NOKIA"),
    Symbol("Nokian Tyres Plc", "TYRES.XHEL", "OMXHEX:TYRES"),
    Symbol("Nordea Bank Abp", "NDA_FI.XHEL", "OMXHEX:NDA_FI"),
    Symbol("Novo Nordisk B A/S", "NOVO_B.XCSE", "OMXCOP:NOVO_B"),
    Symbol("Novozymes B A/S", "NZYM_B.XCSE", "OMXCOP:NZYM_B"),
    Symbol("NVIDIA Corporation", "NVDA", "NASDAQ:NVDA"),
    Symbol("Orion Corporation B", "ORNBV.XHEL", "OMXHEX:ORNBV"),
    Symbol("Outokumpu Oyj", "OUT1V.XHEL", "OMXHEX:OUT1V"),
    Symbol("Pandora A/S", "PNDORA.XCSE", "OMXCOP:PNDORA"),
    Symbol("Pandox AB ser. B", "PNDX_B.XSTO", "OMXSTO:PNDX_B"),
    Symbol("Peab AB ser. B", "PEAB_B.XSTO", "OMXSTO:PEAB_B"),
    Symbol("PowerCell Sweden AB", "PCELL.XSTO", "OMXSTO:PCELL"),
    Symbol("Ratos AB ser. B", "RATO_B.XSTO", "OMXSTO:RATO_B"),
    Symbol("Samhällsbyggnadsbo. i Norden AB ser. B", "SBB_B.XSTO", "OMXSTO:SBB_B"),
    Symbol("Sampo Plc A", "SAMPO.XHEL", "OMXHEX:SAMPO"),
    Symbol("Sandvik AB", "SAND.XSTO", "OMXSTO:SAND"),
    Symbol("SAS AB", "SAS.XSTO", "OMXSTO:SAS"),
    Symbol("Scandic Hotels Group AB", "SHOT.XSTO", "OMXSTO:SHOT"),
    Symbol("Securitas AB ser. B", "SECU_B.XSTO", "OMXSTO:SECU_B"),
    Symbol("Sedana Medical AB", "SEDANA.XSTO", "OMXSTO:SEDANA"),
    Symbol("Skandinaviska Enskilda Banken ser. A", "SEB_A.XSTO", "OMXSTO:SEB_A"),
    Symbol("Skanska AB ser. B", "SKA_B.XSTO", "OMXSTO:SKA_B"),
    Symbol("SKF, AB ser. B", "SKF_B.XSTO", "OMXSTO:SKF_B"),
    Symbol("SkiStar AB ser. B", "SKIS_B.XSTO", "OMXSTO:SKIS_B"),
    Symbol("Societe Generale SA", "GLE.XPAR", "EURONEXT:GLE"),
    Symbol("Spotify Technology SA", "639.XETRA", "XETR:639"),
    Symbol("SSAB AB ser. A", "SSABAH.XHEL", "OMXHEX:SSABAH"),
    Symbol("Stillfront Group AB", "SF.XSTO", "OMXSTO:SF"),
    Symbol("Stora Enso Oyj R", "STEAV.XHEL", "OMXHEX:STEAV"),
    Symbol("Storytel AB ser. B", "STORY_B.XSTO", "OMXSTO:STORY_B"),
    Symbol("Svenska Cellulosa AB SCA ser. B", "SCA_A.XSTO", "OMXSTO:SCA_A"),
    Symbol("Svenska Handelsbanken ser. A", "SHB_A.XSTO", "OMXSTO:SHB_A"),
    Symbol("SWECO AB ser. B", "SWEC_B.XSTO", "OMXSTO:SWEC_B"),
    Symbol("Swedbank AB ser A", "SWED_A.XSTO", "OMXSTO:SWED_A"),
    Symbol("Swedish Match AB", "SWMA.XSTO", "OMXSTO:SWMA"),
    Symbol("Swedish Orphan Biovitrum AB", "SOBI.XSTO", "OMXSTO:SOBI"),
    Symbol("Tele2 AB ser. B", "TEL2_B.XSTO", "OMXSTO:TEL2_B"),
    Symbol("TELENOR", "TEL.XOSL", "OSL:TEL"),
    Symbol("Telia Company AB", "TELIA1.XHEL", "OMXHEX:TELIA1"),
    Symbol("Trelleborg AB ser. B", "TREL_B.XSTO", "OMXSTO:TREL_B"),
    Symbol("Twitter Inc", "TWTR", "NASDAQ:TWTR"),
    Symbol("UPM-Kymmene Corporation", "UPM.XHEL", "OMXHEX:UPM"),
    Symbol("Veoneer Inc. SDB", "VNE_SDB.XSTO", "OMXSTO:VNE_SDB"),
    Symbol("Vestas Wind Systems A/S", "VWS.XCSE", "OMXCOP:VWS"),
    Symbol("Volkswagen AG", "VOW.XETRA", "XETR:VOW"),
    Symbol("Volvo, AB ser. B", "VOLV_B.XSTO", "OMXSTO:VOLV_B"),
    Symbol("Walt Disney Company (The)", "DIS", "NYSE:DIS"),
    Symbol("Wärtsilä Corporation", "WRT1V.XHEL", "OMXHEX:WRT1V"),
    Symbol("YARA INTERNATIONAL", "YARO.XSTO", "OMXSTO:YARO"),
    Symbol("Zalando SE", "ZAL.XETRA", "XETR:ZAL"),
]
